# Generated by Django 3.0.3 on 2020-03-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='meaasge',
            new_name='message',
        ),
    ]
